# Generated by Django 4.2 on 2023-04-08 10:06

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=500)),
                ('content', django_quill.fields.QuillField()),
                ('read_time', models.IntegerField(default=1)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.chapter')),
                ('keywords', models.ManyToManyField(to='Dashboard.keyword')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='of_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.class'),
        ),
    ]
