# Generated by Django 4.2 on 2023-04-08 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_alter_chapter_description_alter_class_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='McqOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mcq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('answer', models.TextField(blank=True, max_length=500, null=True)),
                ('options', models.ManyToManyField(to='Dashboard.mcqoption')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.topic')),
            ],
        ),
    ]
