# Generated by Django 4.2 on 2023-04-08 10:28

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_mcqoption_mcq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='description',
            field=django_quill.fields.QuillField(default=''),
        ),
    ]
