# Generated by Django 4.2 on 2023-04-09 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_useranswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='answer',
            new_name='marked_correct',
        ),
    ]
