# Generated by Django 4.2 on 2023-04-22 09:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_rename_answer_useranswer_marked_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='Dashboard.mcqoption'),
        ),
        migrations.CreateModel(
            name='ExamPapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=10485760, upload_to='exam_papers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt'])])),
                ('name', models.CharField(max_length=256)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.chapter')),
                ('of_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exampaper_class', to='Dashboard.class')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.topic')),
            ],
        ),
        migrations.CreateModel(
            name='CheatSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=10485760, upload_to='cheat_sheet/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt'])])),
                ('name', models.CharField(max_length=256)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.chapter')),
                ('of_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheat_sheet_class', to='Dashboard.class')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.topic')),
            ],
        ),
        migrations.CreateModel(
            name='CaseStudies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=10485760, upload_to='case_studies/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt'])])),
                ('name', models.CharField(max_length=256)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.chapter')),
                ('of_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_studies_class', to='Dashboard.class')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.topic')),
            ],
        ),
    ]
