# Generated by Django 4.2 on 2023-04-22 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_alter_useranswer_option_exampapers_cheatsheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudies',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.chapter'),
        ),
        migrations.AlterField(
            model_name='casestudies',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.topic'),
        ),
        migrations.AlterField(
            model_name='cheatsheet',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.chapter'),
        ),
        migrations.AlterField(
            model_name='cheatsheet',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.topic'),
        ),
        migrations.AlterField(
            model_name='exampapers',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.chapter'),
        ),
        migrations.AlterField(
            model_name='exampapers',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.topic'),
        ),
    ]
