name: SchoolChapter Docker Image CI Pipeline

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  docker:
    runs-on: self-hosted
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v2

      - name: Pulling from git
        run: |
          cd /root/temporary/school-chapter
          sudo git pull origin master --ff

      - name: Down containers
        run: |
          cd /root/temporary/school-chapter
          sudo docker-compose -f "docker-compose.yml" down

      - name: Build image
        run: |
          cd /root/temporary/school-chapter
          sudo docker-compose -f "docker-compose.yml" build

      - name: Run containers
        run: |
          cd /root/temporary/school-chapter
          sudo docker-compose -f "docker-compose.yml" up -d
