name: Docker Image CI

on:
  pull_request:
    branches: [qa]
    types: [closed]

jobs:
  docker:
    runs-on: Qa
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v2

      - name: Pulling from git
        run: |
          cd /home/ubuntu/cvc_dev/cvc-job-assignment
          sudo git pull origin qa --ff

      - name: Down containers
        run: |
          cd /home/ubuntu/cvc_dev/cvc-job-assignment
          sudo docker compose -f "docker-compose.yml" down

      - name: Build image
        run: |
          cd /home/ubuntu/cvc_dev/cvc-job-assignment
          sudo docker compose -f "docker-compose.yml" build

      - name: Run containers
        run: |
          cd /home/ubuntu/cvc_dev/cvc-job-assignment
          sudo docker compose -f "docker-compose.yml" up -d

      - name: Slack Notification
        if: always()
        run: |
          curl --location --request POST 'https://hooks.slack.com/services/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' --header 'Accept: application/json' --header 'Content-Type: application/json' --data-raw '{ "blocks": [ { "type": "divider" }, { "type": "section", "text": { "type": "mrkdwn", "text": "`@${{ github.actor }}` has started deploying `${{ github.head_ref }}`  to *qa* of `${{ github.repository }}` to Environment : *${{ github.job }}*  os : *ubuntu* \n\n\n\n Deoplyment: ${{ job.status }}" }, "accessory": { "type": "image", "image_url": "https://avatars.githubusercontent.com/${{ github.actor }}", "alt_text": "cute cat" } }, { "type": "section", "text": { "type": "mrkdwn", "text": "Latest Changes in this deployment: <https://github.com/adcuratio/cvc-job-assignment/pull/${{ github.event.pull_request.number }}|Go to PR page>" } }, { "type": "divider" } ] }'
